### ISSUE TITLE
Use `void` instead of `u0`

### ISSUE THREAD

**Issue by SpexGuy** [nektro/zig-range#1]
A common mistake when using this library could be to omit the first parameter, like this:
```zig
for (range(100)) |i| {
    array[i] = 4;
}
```
With `u0` as the slice type, this code will compile, but will not have the intended behavior.  The range function should return a slice of `void` instead, so that this is a compile error.  Or, alternatively,
```zig
const @"Use |_, i| instead of |i|" = struct {};
pub fn range(len: usize) []const @"Use |_, i| instead of |i|" {
    ...
}
```

**Comment by nektro** [comment]
good idea :)
